# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_position', models.IntegerField(verbose_name='Position Number')),
                ('car_name', models.CharField(max_length=100, verbose_name='Car Name')),
                ('car_color', models.CharField(max_length=20, verbose_name='Car Color')),
            ],
        ),
    ]
